== Sample codes

Here I will present a JUnit5 test class link:https://github.com/kazurayam/ashotwrapper/blob/develop/src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[`com.kazurayam.ashotwrapper.samples.AShotWrapperDemo`] to demonstrate how to use the `AShotWrapper` class.

The test class starts with the package statement, import statements, class declaration and some common boilerplate methods; it is as follows:

[quote]
----
include::../src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[lines=1..69]
----

Now I will show each test methods that demonstrates how to use AShotWrapper, with resulting image files.

=== Save a screenshot of the entire page in PNG

The following code takes a screenshot of entire page view of the link:https://www.iana.org/domains/reserved[target URL], save the image in a PNG file.

[source]
----
include::../src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[lines=89..95]
----

OUTPUT: link:https://kazurayam.github.io/ashotwrapper/samples/com.kazurayam.ashotwrapper.samples.AShotWrapperDemo/test_saveEntirePageImage.png[entire page screenshot in PNG]

=== Save a screenshot of the current viewport in PNG

The following code takes a screenshot of current viewport of the link:https://www.iana.org/domains/reserved[target web page] in the browser (not the entire page screenshot), save the image in a PNG file.

[source]
----
include::../src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[lines=118..124]
----

OUTPUT: link:https://kazurayam.github.io/ashotwrapper/samples/com.kazurayam.ashotwrapper.samples.AShotWrapperDemo/test_savePageImage.png[current viewport screenshot in PNG]


=== Save a screenshot of an element in the page in PNG

You can select a single HTML element in the link:http://example.com/[target web page], take the screenshot of the element, and save the image into a PNG file.

[source]
----
include::../src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[lines=127..137]
----

OUTPUT: link:https://kazurayam.github.io/ashotwrapper/samples/com.kazurayam.ashotwrapper.samples.AShotWrapperDemo/test_saveElementImage.png[element screenshot in PNG]


=== Save a screenshot of the entire page in JPEG

You can save screenshot images into files in JPEG format. In some cases, a screenshot in JPEG of a web page can be much smaller than PNG.

[source]
----
include::../src/test/java/com/kazurayam/ashotwrapper/samples/AShotWrapperDemo.java[lines=97..103]
----

OUTPUT: link:https://kazurayam.github.io/ashotwrapper/samples/com.kazurayam.ashotwrapper.samples.AShotWrapperDemo/test_saveEntirePageImageAsJpeg.jpg[entire page screenshot in JPEG]

You can also take screenshot of current viewport and selected HTML element in JPEG as well.
